name: Pull request tests

permissions:
  contents: read

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  platform-tests:
    uses: ./.github/workflows/platforms.yml
